# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to an existing IKS cluster

name: Build and Deploy to IKS

# Execute on every push to the default branch. Merging a pull request counts as a push.
on:
  push:
    branches:
      - try-composite-actions

jobs:
  build-push-deploy-job:
    runs-on: ubuntu-latest
    name: A job to download and log into ibmcloud cli
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          echo ${{ secrets.VCAP_LOCAL }} >> ./web/api/vcap-local.json
          echo REACT_APP_MAPBOX_ACCESS_TOKEN=${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }} >> ./web/client/.env.local
      - id: iks-deploy
        uses: call-for-code/build-push-deploy@v1
        with:
          cloud-api-key: ${{ secrets.IBM_CLOUD_API_KEY }}
          cloud-region: us-south
          deployment-name: openeew-dashboard
          github-sha: ${{ github.sha }}
          icr-namespace: openeew-test
          image-name: dashboard-gha-test
          k8s-cluster-name: bvucbrsw0jq4m9h0kdag
          k8s-cluster-namespace: openeew-dev
          registry-hostname: us.icr.io
