on: [push]

jobs:
  build-push-deploy-job:
    runs-on: ubuntu-latest
    name: A job to download and log into ibmcloud cli
    steps:
    - uses: actions/checkout@v2
    - name : Set environment variables
      run : | 
          echo ${{ secrets.VCAP_LOCAL }} >> ./web/api/vcap-local.json
          echo REACT_APP_MAPBOX_ACCESS_TOKEN=${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }} >> ./web/client/.env.local
    - id: iks-deploy
      uses: edrian-playground/composite-actions@v1
      with:
        github-sha: v99
        cloud-api-key: ${{ secrets.IBM_CLOUD_API_KEY }}
        cloud-region: us-south
        icr-namespace: openeew-test
        registry-hostname: us.icr.io
        image-name: dashboard-gha-test
        k8s-cluster-name: bvucbrsw0jq4m9h0kdag
        deployment-name: openeew-dashboard
        k8s-cluster-namespace: openeew-dev
